### ISSUE TITLE
create UIs wireframe for tablet/mobile

### ISSUE THREAD

**Issue by bigaru** [inseri-swiss/inseri#38]

**Comment by bigaru** [comment]
* dashboard
    * change text to search
    * add filter icon
* add dropdown for page between project name and status
* add save button
* indicate that items are dropped on drop input
* expanded drop input:
    *  add App Name on top left
    * expand fully similiar to dataflow
* make new sidebar item 'output of apps'

**Comment by aplamada** [comment]
since we want to use WordPress this is no longer needed.
