### ISSUE TITLE
update landing page - http://inseri.swiss/

### ISSUE THREAD

**Issue by aplamada** [inseri-swiss/inseri#55]
- [x] use https://github.com/inseri-swiss/landing-page
- [x] enforce [https](https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https)
- [x] point www to landing page

**Comment by aplamada** [comment]
- [x] detach https://github.com/inseri-swiss/landing-page

**Comment by bigaru** [comment]
okay, I created support ticket #1661191
